id = "less"
name = "LESS"
description = "LESS language support"
version = "0.0.1"
schema_version = 1
authors = ["jimliang <769925821@qq.com>"]
repository = "https://github.com/jimliang/zed-less"

[grammars.less]
repository = "https://github.com/jimliang/tree-sitter-less"
commit = "b3654358011022c274c37a51c8b8957f388c0f72"

[language_servers.less-language-server]
name = "LESS Language Server"
language = "LESS"
