id = "less"
name = "LESS"
description = "LESS language support"
version = "0.1.0"
schema_version = 1
authors = ["jimliang <769925821@qq.com>"]
repository = "https://github.com/jimliang/zed-less"

[grammars.less]
repository = "https://github.com/jimliang/tree-sitter-less"
commit = "307541e7b4d9d890a0d85bd9acf7da777d26d323"

[language_servers.less-language-server]
name = "LESS Language Server"
language = "LESS"
